#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');

Yii::setAlias('@root', $rootPath); //root alias is required for builder to work

$configBuilder = new \yii\configbuilder\ConfigBuilder();
(new yii\web\Application($configBuilder->getWebConfig()))->run();

$application = new yii\console\Application($configBuilder->getConsoleConfig()));
$exitCode = $application->run();
exit($exitCode);
